config/routes.rb
Interfreedom::Application.routes.draw do

  resources :withdraws

  resources :messages

  resources :guest_books

  get "payment_notifications/create"

  get "locales/change_locale"

  resources :payment_notifications  do
    collection do
      get 'pay_pal_payment'
    end
  end
  filter :locale

   ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :settings

  resources :products do
    post :rate, :on => :member
  end

  resources :users do
    post :rate, :on => :member
  end

  resources :cart do
    collection do
      get 'add_item'
      put 'quantity'
    end
  end

  resources :products do
    resources :comments
  end
  resources :orders do
    collection do
      get 'authorization'
      post 'login'
      post 'register'
    end
  end

  namespace :profile do
    resources :orders

    resources :products do
      collection do
        get 'load_product_type'
      end
    end

  end

  resources :profile do
    collection do
      get 'info'
      get 'make_as_saler'
    end
  end

  resources :comments
  resources :searches
  match '/search' => 'searches#index', :as => :search

  resources :supports

  root :to => 'home#index'

  resources :home

end

app/views/shared/_cart_widget.html.haml
-#encoding: utf-8
.span-6.last
  .span-6.last.sbar_head
    #title
      = link_to t('.cart'), cart_index_path
  .span-6.last
    .sbar_content
      - total_quantity = 0.0
      - cart_products.each do |product|
        - total_quantity = product.price * current_cart.item_quantity(product.id) + total_quantity
        .row.cart_item{:id=> product.id}
          = current_cart.item_quantity(product.id)
          x
          = link_to truncate(product.name, :length => 20),categoried_product_path(product), :title => product.name
          %span{:style=>'float:right;'}
            = product.price
            = link_to image_tag('site/webicons/x-red.gif'), '#'
      .row{:style=>'border-top: 1px solid #DDDDDD;text-align:right;'}
        = t('.total')
        = total_quantity
:css
  .cart_item{
    padding:5px;
  }

:javascript
  $('.sbar_content span a ').click(
    function(){
    var product_id = $('div.sbar_content div[id]').attr('id');
   $(this).parents('.cart_item').hide('slow', function(){
      $(this).remove();
   });
   $.post("#{cart_index_url}/" + product_id, {_method:'delete'},null,'script');
    });

app/views/shared/_comment_widget.html.haml
-#encoding: utf-8
.span-6.last
  .span-6.last.sbar_head
    #title
      =  t('.recent_comments')
  .span-6.last
    .sbar_content
      - Comment.where(:commentable_type => 'Product').limit(5).each do |comment|
        - if comment.commentable
          .box
            %label{:style=>'color:grey; font-size:xx-small;'}
              =comment.author
              .right
                = comment.commentable.try(:product_type)
                = ':'
                = link_to comment.commentable.name,  categoried_product_path(comment.commentable)
              %hr
            = comment.text

app/views/shared/_header.html.haml
-#encoding: utf-8
#header.container.prepend-top
  .span-24
    #user_header
      .span-10
        -#= t('shared.header.welcome')
        .right
          (
          - if current_user
            = link_to t('.sign_out'), destroy_user_session_path, :method => :delete
          -else
            = link_to t(:sign_in), new_user_session_path
            |
            = link_to t(:sign_up), new_user_registration_path
          )
          %span{:style =>'padding-left:50px;'}
            - if user_signed_in?
              =link_to t('.profile_link'), profile_index_path
      #user_cart.span-7
        = image_tag 'icons/header_cart.png'
        = link_to t('.cart'), cart_index_path
        = t('shared.header.product', :count=> current_cart.items.count )
      #language.span-4.right
        %ul
          %li
            -#- I18n.available_locales.each do |locale|
            - [:en,:ua].each do |locale|
              - if I18n.locale.eql?(locale)
                -active_locale = :active
              = link_to image_tag("flags/#{locale}.png"), locales_change_locale_path(:locale => locale), :class => active_locale, :title => t(locale)
    #nav.span-24
      #logo.span-8
        %h1.title
          = link_to image_tag('logo.png'), root_path
      = render :partial => 'shared/menu'
      #search-bar.span-10
        -#- @search ||= Search.new
        = form_for :search , :url => search_url do |f|
          = text_field_tag 'search[value]'
          = f.submit t(:search)

app/views/shared/_menu.html.haml
#menu.span-15.last.right
  %ul
    %li= link_to t('.support'), new_support_path
    %li= link_to t('.guest_book'), guest_books_path
    %li= link_to t('.video'), videos_path
    %li= link_to t('.audio'), audios_path
    %li= link_to t('.home'), root_path

    -#TODO make menu links addable from plugin