config/routes.rb
Interfreedom::Application.routes.draw do

  resources :withdraws

  resources :messages

  resources :guest_books

  get "payment_notifications/create"

  get "locales/change_locale"

  resources :payment_notifications  do
    collection do
      get 'pay_pal_payment'
    end
  end
  filter :locale

   ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :settings

  resources :products do
    post :rate, :on => :member
  end

  resources :users do
    post :rate, :on => :member
  end

  resources :cart do
    collection do
      get 'add_item'
      put 'quantity'
    end
  end

  resources :products do
    resources :comments
  end
  resources :orders do
    collection do
      get 'authorization'
      post 'login'
      post 'register'
    end
  end

  namespace :profile do
    resources :orders

    resources :products do
      collection do
        get 'load_product_type'
      end
    end

  end

  resources :profile do
    collection do
      get 'info'
      get 'make_as_saler'
    end
  end

  resources :comments
  resources :searches
  match '/search' => 'searches#index', :as => :search

  resources :supports

  root :to => 'home#index'

  resources :home

end

app/models/support.rb
# -*- encoding : utf-8 -*-
class Support < ActiveRecord::Base
  validates :email,   
            :presence => true,   
            :format => { :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i }  
end    

app/controllers/supports_controller.rb
# -*- encoding : utf-8 -*-
class SupportsController < ApplicationController
  def index

  end

  def new
    @support = Support.new
  end

  def create
    support = Support.new(params[:support])
    if support.save
      redirect_to root_path, :notice => t('.will_read'), :locales =>{:locale => params[:locale] }
    end
  end
end

app/helpers/supports_helper.rb
# -*- encoding : utf-8 -*-
module SupportsHelper
end

app/views/supports/_form.html.haml
= form_for @support do |f|
  -if @support.errors.any?
    #error_explanation
      %h2= "#{pluralize(@support.errors.count, "error")} prohibited this support from being saved:"
      %ul
        - @support.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :subject
    %br
    = f.text_field :subject
  .field
    = f.label :email
    %br
    = f.email_field :email
  .field
    = f.label :message
    %br
    = f.text_area :message, :rows => 5
  .actions
    = f.submit t(:submit)

app/views/supports/edit.html.haml
%h1 Editing support

= render 'form'

= link_to 'Show', @support
\|
= link_to 'Back', supports_path

app/views/supports/index.html.haml
%h1 Listing supports

%table
  %tr
    %th Subject
    %th Email
    %th Message
    %th
    %th
    %th

  - @supports.each do |support|
    %tr
      %td= support.subject
      %td= support.email
      %td= support.message
      %td= link_to 'Show', support
      %td= link_to 'Edit', edit_support_path(support)
      %td= link_to 'Destroy', support, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Support', new_support_path

app/views/supports/new.html.haml
%h1= t('.new_support')

= render 'form'

app/views/supports/show.html.haml
%p#notice= notice

%p
  %b Subject:
  = @support.subject
%p
  %b Email:
  = @support.email
%p
  %b Message:
  = @support.message

= link_to 'Edit', edit_support_path(@support)
\|
= link_to 'Back', supports_path