config/routes.rb
Interfreedom::Application.routes.draw do

  resources :withdraws

  resources :messages

  resources :guest_books

  get "payment_notifications/create"

  get "locales/change_locale"

  resources :payment_notifications  do
    collection do
      get 'pay_pal_payment'
    end
  end
  filter :locale

   ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}

  resources :settings

  resources :products do
    post :rate, :on => :member
  end

  resources :users do
    post :rate, :on => :member
  end

  resources :cart do
    collection do
      get 'add_item'
      put 'quantity'
    end
  end

  resources :products do
    resources :comments
  end
  resources :orders do
    collection do
      get 'authorization'
      post 'login'
      post 'register'
    end
  end

  namespace :profile do
    resources :orders

    resources :products do
      collection do
        get 'load_product_type'
      end
    end

  end

  resources :profile do
    collection do
      get 'info'
      get 'make_as_saler'
    end
  end

  resources :comments
  resources :searches
  match '/search' => 'searches#index', :as => :search

  resources :supports

  root :to => 'home#index'

  resources :home

end

app/models/product.rb
# -*- encoding : utf-8 -*-
class Product < ActiveRecord::Base
  scope :video, where(:product_type => 'Video')
  scope :audio, where(:product_type => 'Audio')

  before_save :set_genre
  before_update :set_genre
  ajaxful_rateable :stars => 5, :dimensions => [:speed], :allow_update => true

  translates :name, :description, :fallbacks_for_empty_translations => true
  globalize_accessors :locales => [:en, :ua], :attributes => [:name, :description]

  include ExtensionInitializer

  paginates_per 9
  #before_validation :set_product_type_id
  belongs_to :user
  #belongs_to :genre
  has_many :order_items
  #belongs_to :product_type, :as => :product_content
  validates_presence_of :name, :product_type
  acts_as_commentable
  has_attached_file :image, :styles => {:large => "270x270>", :medium => '150x150',
                                        :thumb => "50x50"}, :default_url => '/system/images/:style/missing.png',
                    :url => "system/images/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/system/images/:id/:style/:basename.:extension"
  attr_accessor :genre

  attr_accessible :genre, :genre_id, :producer, :image, :name, :description, :product_type,
                  :product_type_id, :image, :style, :group, :album, :count_on_hand, :available_on,
                  :name_en, :name_ua, :description_en, :description_ua, :price
  validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']
  attr_reader :video_product_type_id

  def available?
    if self.available_on.nil? or self.available_on > DateTime.parse(Time.now.to_s)
      false
    else
      true
    end
  end

  def genre
    if @genre.nil? && !genre_id.nil?
      @genre = Genre.find(self.genre_id).name
    end
    @genre
  end

  def set_product_type_id
    self.product_type_id = ProductType.find_by_name(self.product_type).id
  end

  def set_genre
    self.genre_id = Genre.find_or_create_by_name(self.genre).id
  end
end

app/models/product_type.rb
# -*- encoding : utf-8 -*-
class ProductType < ActiveRecord::Base
  has_many :products
  validates_uniqueness_of :name
  #validates_presence_of :name

  def self.video
    @video ||= ProductType.find_by_name('Video')
  end

  def self.audio
    @audio ||= ProductType.find_by_name('Audio')
  end
end

app/controllers/products_controller.rb
# -*- encoding : utf-8 -*-
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    if params[:category_type].present?
      @products = case params[:category_type].to_s
                    when 'video' then
                      Product.videos
                  end
    else
      @products = Product.all
    end

    respond_to do |format|
      format.html # info.html.haml
      format.json { render :json => @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new
    @video = Video.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, :notice => 'Product was successfully created.' }
        format.json { render :json => @product, :status => :created, :location => @product }
      else
        format.html { render :action => "new" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, :notice => 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :ok }
    end
  end


   def rate
    @product = Product.find(params[:id])
    @product.rate(params[:stars], current_user, params[:dimension])
    average = @product.rate_average(true, params[:dimension])
    width = (average / @product.class.max_stars.to_f) * 100
    render :json => {:id => @product.wrapper_dom_id(params), :average => average, :width => width}
  end
end

app/controllers/profile/products_controller.rb
# -*- encoding : utf-8 -*-
class FilterBox
  def initialize(keys = {})
   unless keys.nil?
    if keys[:product_type].blank?
      @product_type = nil
    else
      @product_type = keys[:product_type]
    end
    
   end
    @date_from = nil
    @date_to = nil
    set_date keys
  end
 
  attr_reader :date_to, :date_from, :product_type
  
  def set_date(date_hash)
    unless date_hash.nil? || date_hash[:date_from].nil? || date_hash[:date_to].nil?
      (@date_from = date_hash[:date_from].to_date) ? !date_hash[:date_from].blank? : @date_from = nil
      (@date_to = date_hash[:date_to].to_date) ? !date_hash[:date_to].blank? : @date_to = nil
    end
  end

  #def from
  #@date_from
  #end

  #def to
  #@date_to
  #end
end

class Profile::ProductsController < ApplicationController
  filter_access_to :all
  layout 'profile'

  def index
    @products = products_list = current_user.products.page(params[:page])
    @filter_box = FilterBox.new params[:filter_box]
    unless @filter_box.date_from.nil? || @filter_box.date_to.nil?
      @products = @products.where('products.updated_at between ? and ?', @filter_box.date_from, @filter_box.date_to)
    else
      @products = @products.where('products.updated_at < ?', @filter_box.date_to) unless @filter_box.date_to.nil?
      @products = @products.where('products.updated_at > ?', @filter_box.date_from) unless @filter_box.date_from.nil?
    end 
    @products = @products.where :product_type => @filter_box.product_type unless @filter_box.product_type.nil?
    @products
  end

  def show
    @product  = current_user.products.find_by_id(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def new
    @product =Product.new
  end

  def create
    @product = Product.new(params[:product])
    @product.user = current_user
    if @product.save
      Target.create(:user_id => current_user.id, :product_id => @product.id)
      redirect_to profile_products_path, :notice => 'Product was successfuly created.'
    else 
      render :action => :edit
    end
  end

  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to profile_products_path, :notice => 'Product was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  def load_product_type
    render :partial => "#{params[:product_type].downcase}", 
      :locals => {:product => Product.new, :locale => params[:locale]}
  end
end

app/helpers/products_helper.rb
# -*- encoding : utf-8 -*-
module ProductsHelper
  def product_states(product)
    new = ''
    if product.created_at >= 2.weeks.ago
      new = "<div class='state'> NEW </div>"
    end
    if product.available?
      available = "<div class='state'> AVAILABLE </div>"
    else
      available = "<div class='state'>NOT AVAILABLE </div>"
    end
    #if new.nil?
      #raw available
    #else
      raw new + available
    #end
  end

  def categoried_product_path(product)
    instance_eval (product.product_type.downcase + '_path product')
  end
end

app/helpers/profile/products_helper.rb
# -*- encoding : utf-8 -*-
module Profile::ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product, :html => { :multipart => true }   do |f|
  -if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :avalible_on
    = f.text_field :avalible_on
  .field
    = f.label :count_on_hand
    = f.number_field :count_on_hand
  -#.field
  -#  = f.label :category
  -#  = f.text_field :category
  .field
    = f.label :image
    = f.file_field :image
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products
-#
-#%table
-#  %tr
-#    %th Name
-#    %th Description
-#    %th Avalible on
-#    %th Count on hand
-#    %th Category
-#    %th
-'add'#    %th
-#    %th
- @products.each do |product|
  .product.column
    .span-4
      = link_to image_tag(product.image.url(:medium)), product_path(product)
    .span-13
      .span-9
        #states.span-9
          = product_states(product)
        .span-9.prepend-top
          %h4
            = link_to product.name, product_path(product)
        .span-9.last
          = truncate product.description, :length=> 210
      .span-3
        = link_to 'add',add_item_cart_index_path(:product_id => product)


-#    %tr
-#      %td= image_tag product.image.url(:thumb)
-#      %td= product.name
-#      %td= product.description
-#      %td= product.avalible_on
-#      %td= product.count_on_hand
-#      -#%td= product.category
-#      %td= link_to 'Show', product
-#      %td= link_to 'Edit', edit_product_path(product)
-#      %td= link_to 'Destroy', product, :confirm => 'Are you sure?', :method => :delete
-#
-#%br
-#
-#= link_to 'New Product', new_product_path

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
-#%p#notice= notice
-#
-#%p
-#  %b Name:
-#  = @product.name
-#%p
-#  %b Description:
-#  = @product.description
-#%p
-#  %b Avalible on:
-#  = @product.avalible_on
-#%p
-#  %b Count on hand:
-#  = @product.count_on_hand
-#%p
-#  %b Category:
-#  = @product.category
-#
-#= link_to 'Edit', edit_product_path(@product)
-#\|
-#= link_to 'Back', products_path
-#